SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_PROCESSOR i686)
SET(TARGET_TRIPLE i686-elf)

SET(TOOLCHAIN_PREFIX ${TARGET_TRIPLE}-)

SET(CROSS_COMPILER_ROOT_DIR "/home/konstantin.kalinin/opt/cross/bin/")

SET(CMAKE_C_COMPILER   ${CROSS_COMPILER_ROOT_DIR}${TARGET_TRIPLE}-gcc)
SET(CMAKE_ASM_COMPILER ${CROSS_COMPILER_ROOT_DIR}${TARGET_TRIPLE}-gcc)
SET(CMAKE_CXX_COMPILER ${CROSS_COMPILER_ROOT_DIR}${TARGET_TRIPLE}-g++)
SET(CMAKE_OBJCOPY      ${CROSS_COMPILER_ROOT_DIR}${TARGET_TRIPLE}-objcopy)
SET(CMAKE_AR           ${TOOLCHAIN_PREFIX}ar)
SET(CMAKE_RANLIB       ${TOOLCHAIN_PREFIX}ranlib)
SET(CMAKE_LD           ${TOOLCHAIN_PREFIX}ld)

SET(ASSEMBLER_BIN nasm)

SET(CMAKE_C_FLAGS_INIT "-ffreestanding -nostdlib -m32 -Wall -Wextra")
SET(CMAKE_CXX_FLAGS_INIT "-ffreestanding -nostdlib -m32 -Wall -Wextra -fno-exceptions -fno-rtti")
SET(CMAKE_EXE_LINKER_FLAGS_INIT "-m32 -nostdlib")

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)